#! /bin/sh
# /etc/init.d/jupyter_service
#

# Some things that run always
touch /var/lock/jupyter_service

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Jupyter Service ..."
    /sbin/runuser cloudera -s /bin/bash -c "/home/cloudera/start_jupyter.sh"
    ;;
  stop)
    echo "Stopping Jupyter Service ..."
    echo "Could do more here"
    ;;
  *)
    echo "Usage: /etc/init.d/jupyter_service {start|stop}"
    exit 1
    ;;
esac

exit 0
